### ISSUE TITLE
V0

### ISSUE THREAD

**Issue by heitorpolidoro** [heitorpolidoro/bartholomew-smith#1]
- [x] heitorpolidoro/bartholomew-smith#3
- [x] heitorpolidoro/bartholomew-smith#4
- [x] heitorpolidoro/bartholomew-smith#5
- [x] heitorpolidoro/bartholomew-smith#6
