### ISSUE TITLE
Resolve better the timeout issue 

### ISSUE THREAD

**Issue by heitorpolidoro** [heitorpolidoro/bartholomew-smith#106]
- [x] heitorpolidoro/bartholomew-smith#111
- [x] heitorpolidoro/bartholomew-smith#112
- [x] heitorpolidoro/bartholomew-smith#113
