### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by heitorpolidoro** [heitorpolidoro/bartholomew-smith#82]
- [ ] heitorpolidoro/bartholomew-smith#83
- [ ] heitorpolidoro/bartholomew-smith#84
- [ ] heitorpolidoro/bartholomew-smith#85
- [ ] heitorpolidoro/bartholomew-smith#86
- [ ] heitorpolidoro/bartholomew-smith#87
